apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: &name install-headers
  labels:
    app: *name
spec:
  selector:
    matchLabels:
      app: *name
  template:
    metadata:
      labels:
        app: *name
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - image: "ghcr.io/converged-computing/kernel-header-installer:gke-ubuntu2404"
        name: header-installer
        imagePullPolicy: Always
        command: ["/bin/bash", "/entrypoint.sh"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: modules
          mountPath: /lib/modules
        - name: shared
          mountPath: /opt/shared
      volumes:
      - name: modules
        hostPath:
          path: /lib/modules
      - name: shared
        hostPath:
          path: /opt/shared
          type: DirectoryOrCreate
