apiVersion: batch/v1
kind: Job
metadata:
  name: kripke-caliper
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kripke
        imagePullPolicy: Always
        image: ghcr.io/converged-computing/google-performance-study:kripke-caliper-test
        # mpirun --allow-run-as-root -np 8 kripke --layout DGZ --dset 16 --zones 32,16,8 --gset 16 --groups 16 --niter 500 --legendre 2 --quad 16 --procs 2,2,2
        command: ["/bin/sh", "-c", "sleep infinity"]
        # This is already set
        env:
        - name: CALI_CONFIG_FILE
          value: /caliper.conf         
      
  backoffLimit: 0
