apiVersion: batch/v1
kind: Job
metadata:
  name: kripke-caliper
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: kripke
        imagePullPolicy: Always
        image: ghcr.io/converged-computing/google-performance-study:kripke-caliper-test
        # mpirun --allow-run-as-root -np 8 kripke --layout DGZ --dset 16 --zones 32,16,8 --gset 16 --groups 16 --niter 500 --legendre 2 --quad 16 --procs 2,2,2
        command: ["/bin/sh", "-c", "sleep infinity"]
        # This is already set
        # IMPORTANT: need to unset these after the app run. Likely we want this in an entrypoint.
        # /opt/caliper-build/src/tools/cali-query/cali-query -T /data/out.cali  | less -S
        # /opt/caliper-build/src/tools/cali-query/cali-query -Gj /data/out.cali  | less -S
        # /opt/caliper-build/src/tools/cali-query/cali-query --help spot 
        # For GPUs: profile.cuda,cuda.gputime,profile.hip,rocm.<gputype>
        env:
        - name: CALI_CONFIG
          value: spot,output=/data/out.cali,profile.mpi,timeseries,timeseries.iteration_interval=1,timeseries.maxrows=500,mpi.message.count,mpi.message.size
        - name: CALI_LOG_LOGFILE
          value: /data/output.cali
        - name: CALI_LOG_VERBOSITY
          value: "2"
