apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: osu

spec:
  # The number of pods (and therefore nodes) for this job.
  size: 2
  tasks: 2
  logging:
    quiet: false

  flux:
    optionFlags: "-o cpu-affinity=per-task"
    container:
      disable: true

  containers:
    - image: ghcr.io/converged-computing/google-performance-study:osu-test
      imagePullPolicy: Always      
      command: /usr/libexec/osu-micro-benchmarks/mpi/pt2pt/osu_latency
      resources:
        limits:
          cpu: "46"
        requests:
          cpu: "46"
