apiVersion: batch/v1
kind: Job
metadata:
  name: osu-caliper
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: lammps-worker
        imagePullPolicy: Always
        image: ghcr.io/converged-computing/google-performance-study:osu-caliper-test
        # export CALI_CONFIG_FILE=/caliper-allreduce.conf
        # mpirun --allow-run-as-root -np 8 osu_allreduce
        # export CALI_CONFIG_FILE=/caliper-latency.conf
        # mpirun --allow-run-as-root -np 2 osu_latency
        # install 2.13.0
        command: ["/bin/sh", "-c", "sleep infinity"]
        # This is already set
        # workingDir: /root/.local/share/lammps/bench
        #env:
        #- name: CALI_CONFIG_FILE
        #  value: /caliper.conf         
        #- name: CALI_CONFIG
        #  value: spot,output=/data/out.cali
        # CALI_CONFIG=spot,output=/data/out.cali,profile.mpi,mpi.message.count,mpi.message.size,local_query="group by msg_size",cross_query="select msg_size as size group by msg_size"
        # Treescape (ask Matt)
        # https://github.com/LLNL/thicket
        # https://github.com/LLNL/hatchet
        # https://llnlfed.webex.com/llnlfed/url.php?frompanel=false&gourl=https%3A%2F%2Fsoftware.llnl.gov%2FCaliper%2FEventTracing.html
        env:
        - name: CALI_CONFIG
          value: spot,output=/data/out.cali,profile.mpi,mpi.message.count,mpi.message.size
          value: trace.mpi,event-trace
          # cali-to-trace-event *.cali -> one perfetto from all of caliper
        - name: CALI_LOG_LOGFILE
          value: /data/output.cali
        - name: CALI_LOG_VERBOSITY
          value: "2"
