apiVersion: flux-framework.org/v1alpha2
kind: MiniCluster
metadata:
  name: kripke

spec:
  # The number of pods (and therefore nodes) for this job.
  size: 2
  interactive: true
  logging:
    quiet: false

  flux:
    optionFlags: "-o cpu-affinity=per-task"
    container:
      disable: true

  containers:
    - image: ghcr.io/converged-computing/google-performance-study:kripke-test
      imagePullPolicy: Always
      securityContext:
        privileged: true
      volumes:
        my-empty-dir:
          emptyDir: true
          emptyDirMedium: "memory"        
      resources:
        limits:
          cpu: "46"
        requests:
          cpu: "46"
